[package]
name    = "terminfo"
version = "0.1.3"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

description = "Terminal information."
repository  = "https://github.com/meh/rust-terminfo"
keywords    = ["terminal", "terminfo", "termcap", "term"]

[dependencies]
nom = "2.0"
